version: '3'

services:
  server:
   build: .
   restart: always
   ports:
     - 8080:8080
   depends_on:
     - mysqldb	  
  mysqldb:
    image: "mysql:5.7"
      restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=S5@sankarsh
      - MYSQL_DATABASE=wallpaperapiapp
      - MYSQL_USER=root
      - MYSQL_PASSWORD=S5@sankarsh
    ports:
      - 3307:3306
